### ISSUE TITLE
Nice control, just more effect

### ISSUE THREAD

**Issue by dzungpv** [toannt/MenuButton#1]
Thank for nice control. But I wonder if you can make effect like this or give me a hint.
https://lh3.googleusercontent.com/-k65ZhkNxr_8/VEPuNIAS_8I/AAAAAAAAuyQ/w6WY8Phkmb0/w506-h323/gif-arrow.gif

**Comment by toannt** [comment]
Thanks for suggestion, i'm going to do this as soon as possible :+1:
